# Basic Site Settings
locale                   : "en-US"
title: "ImBishwa"
description: "This is my official personal site, where I put my thoughts, learning and whatever I want. Its not me, its my progress."
url: "https://bishwapuri.com.np" # Add your site URL here
baseurl: "" # Add your baseurl if needed
repository: "workBishwa/imBishwa.github.io"



author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Bishwa Prakash Puri"
  pronouns         : # example: "she/her"  
  bio              : "A boring 😊 yet curious soul 🌱 on a lifelong journey of discovery 🌍. My opinions change 🔄 as I grow 📚, learn 💡, and embrace new perspectives ✨"
  location         : "Kathmandu, Nepal"
  employer         : 
  uri              : https://bishwapuri.com.np/
  email            : "work.bishwapuri@gmail.com"
  linkedin : imbishwapuri




markdown: kramdown
highlighter: rouge

kramdown:
  math_engine: mathjax
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_level: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


timezone: "UTC"
encoding: UTF-8

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 10
paginate_path: "/blog/page:num/"







publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :



# Reading Files
include:
  - .htaccess
  - _pages
  - _subpages
  - files
  - _posts
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn

markdown_ext: "markdown,mkdown,mkdn,mkd,md"



# These settings control how pages and collections are included in the site

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: post
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: post
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: post
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: post
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true




